<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<div style="background-color: white; padding: 10px; display: inline-block;">
    <img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />
</div>

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
# Basic Numpy Arrays

### type

In [556]:
type([1, 2, 3])

list

In [557]:
lst = [11, 12, 13]
print(type(lst))
print(lst)

<class 'list'>
[11, 12, 13]


In [558]:
arr = np.array([14, 15, 16])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([14, 15, 16])


### 😮 printing numpy array and its element

Note: Printing and formatting in `Jupyter Notebook` or `Google Colab` may behave differently compared to standard Python scripts.

In `Jupyter/Colab`, the output of the last executed expression in a cell is automatically displayed, even if you don’t explicitly use print().

This can sometimes lead to confusion, especially when you're comparing outputs or expecting consistent behavior across different environments.

To ensure consistent output and avoid ambiguity, it's recommended to use `print()` explicitly when you want to display results.

In [670]:
a = np.array([1, 2, 3, 4])
print("print using print():")
print(a)

a

print using print():
[1 2 3 4]


array([1, 2, 3, 4])

In [671]:
b = np.array([0, 0.5, 1, 1.5, 2])
print("print using print():")
print(b)

b

print using print():
[0.  0.5 1.  1.5 2. ]


array([0. , 0.5, 1. , 1.5, 2. ])

### 😵‍💫 printing single number also shown differently

for example, numpy prints `np.float64(32.5)` in Jupyter Notebook?!

In Jupyter Notebook, you may notice that variables like `np.float64(32.5)` are displayed with their full type:

✅ Explanation
- Jupyter displays the `repr()` of objects — the developer-focused representation.
- This often includes the data type (np.float64, np.int32, etc.).
- It's different from the regular `print()` function, which uses `str()`, designed for readability.

📝 When does this matter?
- It’s useful for debugging or checking exact data types.
- ut if you only care about the value, use `print()` or format the output yourself.


In [674]:
lst = [3.14, 1, 23, 3.25]
lst[0]

3.14

In [675]:
arr = np.array([32.5, 1, 23, 99.15])
arr[0]

np.float64(32.5)

### indexing

(aware display style)

In [682]:
for x in [a[0], a[1], a[2], a[1], b[1], b[0], b[2]]:
    print(str(x))

1
2
3
2
0.5
0.0
1.0


In [681]:
for x in [a[0], a[1], a[2], a[1], b[1], b[0], b[2]]:
    print(repr(x))

np.int64(1)
np.int64(2)
np.int64(3)
np.int64(2)
np.float64(0.5)
np.float64(0.0)
np.float64(1.0)


more indexing 

In [564]:
a = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print("      a", a)
print("a[-1:3]", a[-1:3])
print("a[-9:5]", a[-9:5])
print("a[1:-1]", a[1:-1])
print(" a[::2]", a[::2])
print(" a[::3]", a[::3])
print("a[::-2]", a[::-2])
print("a[::-1]", a[::-1])

      a [11 12 13 14 15 16 17 18 19 20]
a[-1:3] []
a[-9:5] [12 13 14 15]
a[1:-1] [12 13 14 15 16 17 18 19]
 a[::2] [11 13 15 17 19]
 a[::3] [11 14 17 20]
a[::-2] [20 18 16 14 12]
a[::-1] [20 19 18 17 16 15 14 13 12 11]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Array Data Types

In [565]:
a1 = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [566]:
a1.dtype

dtype('int64')

In [567]:
type(a1[0])

numpy.int64

In [568]:
a2 = np.array([0, 0.5, 1, 1.5, 2])
a2

array([0. , 0.5, 1. , 1.5, 2. ])

In [569]:
a2.dtype

dtype('float64')

In [570]:
print(type(a2[0]))

<class 'numpy.float64'>


In [571]:
# changing/assigning data type when array creation
lst = np.array([3.14, 12.9, 13.0, 14.1], dtype=int)
lst

array([ 3, 12, 13, 14])

In [572]:
print(np.array([11, 12, 13, 14]))  # default by integer
print(np.array([11, 12, 13, 14], dtype=int))
print(np.array([11, 12, 13, 14], dtype=float))

[11 12 13 14]
[11 12 13 14]
[11. 12. 13. 14.]


In [573]:
arr = np.array([True, False, True])
print(arr.dtype, arr)

bool [ True False  True]


In [574]:
arr = np.array(["a", "b", "c"])
print(arr.dtype, arr)  # `Ùnicode String``

<U1 ['a' 'b' 'c']


In [575]:
arr = np.array(["a", "b", "c", 11, 12, 13])
print(arr.dtype, arr)  # `Ùnicode String``

<U21 ['a' 'b' 'c' '11' '12' '13']


To know more about data type see this [document](https://numpy.org/devdocs/reference/arrays.dtypes.html)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)



# Arange & Linspace

### arange vs range
- how numpy arange is differeant from range function in regular python?
- what is the benefits of using arange?
- what is the benefits of using linspace?

In [576]:
print(list(range(10)))
print(list(range(11, 20)))
print(list(range(11, 20, 3)))
print(list(range(20, 11, -3)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 12, 13, 14, 15, 16, 17, 18, 19]
[11, 14, 17]
[20, 17, 14]


In [577]:
# same way
print(np.arange(10))
print(np.arange(11, 20))
print(np.arange(11, 20, 3))
print(np.arange(20, 11, -3))

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[11 14 17]
[20 17 14]


In [578]:
print(np.arange(11, 20, 1.25))  # try if it works in regular python
print(np.arange(1, 2, 0.1))  # try if it works in regular python

[11.   12.25 13.5  14.75 16.   17.25 18.5  19.75]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


### arange vs linspace

In [579]:
np.linspace(0, 1, 20)  # check if last number inclusive

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [580]:
np.linspace(0, 1, 21)  # check i f last number inclusive

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [581]:
np.linspace(0, 1, 20, False)  # check if last number inclusive

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Shape
- reshape or flatten
- number of columns and rows.
- number of elements

lets reshape 2D array to 1D:
### `resahpe()`

In [582]:
# given 1D array
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [583]:
# lets make it to 2D array of 3 rows 4 columns
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [584]:
arr  # note that reshape won't overwrite original array unless you use equal sign

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [585]:
# now you overwrite
arr = arr.reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [586]:
# np.arange(12).reshape(5, 5) # error

Let's make 2D array to 1D:
### `ravel()` or `flatten()`

In [587]:
arr = np.linspace(0, 1, 21).reshape(3, 7)  # given
arr

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65],
       [0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]])

In [588]:
arr.ravel()

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [589]:
arr  # note that this won't overwrite original array unless you use equal sign

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65],
       [0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]])

In [590]:
arr.flatten()  # note that this won't overwrite original array unless you use equal sign

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [591]:
arr

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65],
       [0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]])

### num of cols, rows, dimension, element count

In [592]:
A = np.arange(12).reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [593]:
print("num of rows & cols:", A.shape)
print("dimension:", A.ndim)
print("num of elems:", A.size)

num of rows & cols: (4, 3)
dimension: 2
num of elems: 12


In [594]:
B = np.arange(40)
B = B.reshape(2, 4, 5)
B

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [595]:
print(B.dtype)
print(B.shape)
print(B.ndim)
print(B.size)

int64
(2, 4, 5)
3
40


how would you print column count or row count as integer?

In [596]:
print(B.shape[0])  # row count
print(B.shape[1])  # col count

2
4


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Indexing and Slicing of Matrices

### row indexing

In [597]:
# Square matrix
A = np.arange(101, 141).reshape(5, 8)
A

array([[101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132],
       [133, 134, 135, 136, 137, 138, 139, 140]])

In [598]:
A[2]  # 3rd row NOT 3rd elem

array([117, 118, 119, 120, 121, 122, 123, 124])

In [599]:
print(A[0:-1])
print("")

print(A[1:])
print("")

print(A[:2])
print("")

print(A[1:-1])

[[101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116]
 [117 118 119 120 121 122 123 124]
 [125 126 127 128 129 130 131 132]]

[[109 110 111 112 113 114 115 116]
 [117 118 119 120 121 122 123 124]
 [125 126 127 128 129 130 131 132]
 [133 134 135 136 137 138 139 140]]

[[101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116]]

[[109 110 111 112 113 114 115 116]
 [117 118 119 120 121 122 123 124]
 [125 126 127 128 129 130 131 132]]


In [600]:
A[[3, 1, 2, 3]]  # multi indexing columns

array([[125, 126, 127, 128, 129, 130, 131, 132],
       [109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132]])

In [601]:
A[[3, 1, 2, 3], :]  # multi indexing columns

array([[125, 126, 127, 128, 129, 130, 131, 132],
       [109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132]])

### row & col indexing using comma

In [602]:
A[:, :2]

array([[101, 102],
       [109, 110],
       [117, 118],
       [125, 126],
       [133, 134]])

In [603]:
A[:2, :2]

array([[101, 102],
       [109, 110]])

In [604]:
A[:2, 2:]

array([[103, 104, 105, 106, 107, 108],
       [111, 112, 113, 114, 115, 116]])

### chained indexing vs comma indexing

In [605]:
print(A[1][0])  # chainned indexing
print(A[1, 0])  # comma indexing

# you WILL SEE DIFF SOON!

109
109


In [606]:
print(A[1][:])  # chainned indexing
print(A[1, :])  # comma indexing

# you WILL SEE DIFF SOON!

[109 110 111 112 113 114 115 116]
[109 110 111 112 113 114 115 116]


In [607]:
print(A[:][2])  # chainned indexing
print(A[:, 2])  # comma indexing

# SEE DIFFERANCE?

[117 118 119 120 121 122 123 124]
[103 111 119 127 135]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Vectorized operations (aka broadcasting)

In [608]:
lst = np.array([11, 12, 13, 14])
lst - 100

array([-89, -88, -87, -86])

In [609]:
A  # re-check how A looks like

array([[101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132],
       [133, 134, 135, 136, 137, 138, 139, 140]])

In [610]:
A - 100

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [611]:
A[0] = -23424
A

array([[-23424, -23424, -23424, -23424, -23424, -23424, -23424, -23424],
       [   109,    110,    111,    112,    113,    114,    115,    116],
       [   117,    118,    119,    120,    121,    122,    123,    124],
       [   125,    126,    127,    128,    129,    130,    131,    132],
       [   133,    134,    135,    136,    137,    138,    139,    140]])

In [612]:
# A[1] = np.array([10, 10, 10, 10]) # error
# this is NOT broadcasting. we are assigning list to be fit same sie

In [613]:
A = np.arange(101, 121).reshape(4, 5)
A

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120]])

In [614]:
A[2] = 99
A
# this IS broadcasting! SINGLE INTEGER is propagating to entire row

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [ 99,  99,  99,  99,  99],
       [116, 117, 118, 119, 120]])

In [615]:
# broadcasting is NOT working in regular python
lst = [[11, 12, 13], [10, 10, 10], [17, 18, 19]]

lst[2] = 99

lst

[[11, 12, 13], [10, 10, 10], 99]

In [616]:
np.array([11, 12, 13, 14]) * 100

array([1100, 1200, 1300, 1400])

In [617]:
np.arange(11, 15) - 99

array([-88, -87, -86, -85])

error case

In [618]:
# lst = [11, 12, 13, 14] + 100 # error
# error, "lst + integer" not working in python

### What if you want to do this in regular python?

In [619]:
lst = [11, 12, 13, 14]

In [620]:
lst = [11, 12, 13, 14]
# you need to use for loop (this is much longer process compared to numpy)
[i + 100 for i in lst]

[111, 112, 113, 114]

In [621]:
a = [100, 101, 102, 103]
b = [3, 4, 5, 6]

In [622]:
a + b  # no error but you will get unintended

[100, 101, 102, 103, 3, 4, 5, 6]

In [623]:
np.array(a) + np.array(b)

array([103, 105, 107, 109])

In [624]:
# a * b # error!! you need to use numpy

np.array(a) * np.array(b)

array([300, 404, 510, 618])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Summary statistics

### 1D array stat

In [625]:
a = np.array([31, 32, 33, 34])
a

array([31, 32, 33, 34])

In [626]:
a.sum()

np.int64(130)

In [627]:
np.sum(a)

np.int64(130)

In [628]:
a.mean()

np.float64(32.5)

In [629]:
np.mean(a)  # also works same as above

np.float64(32.5)

In [630]:
a.var()

np.float64(1.25)

In [631]:
np.sqrt(a.var())

np.float64(1.118033988749895)

In [632]:
a.std()  # you now stadard deviation is square root of variance

np.float64(1.118033988749895)

### 2D array stat (introducing axis)

In [633]:
A = np.array(range(31, 35)).reshape(2, 2)
A

array([[31, 32],
       [33, 34]])

In [634]:
A.mean()

np.float64(32.5)

In [635]:
A.mean(axis=0)

array([32., 33.])

In [636]:
A.sum(axis=1)

array([63, 67])

In [637]:
A.sum(axis=0)  # by row (=within row X), vertically

array([64, 66])

In [638]:
A.sum(axis=1)  # by col (=within col X), horizontally

array([63, 67])

In [639]:
A = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

In [640]:
A.sum(), A.mean(), A.var(), A.std()

(np.int64(135),
 np.float64(15.0),
 np.float64(6.666666666666667),
 np.float64(2.581988897471611))

In [641]:
A.sum(axis=0), A.sum(axis=1)

(array([42, 45, 48]), array([36, 45, 54]))

In [642]:
A.mean(axis=0), A.mean(axis=1)

(array([14., 15., 16.]), array([12., 15., 18.]))

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Logical Indexing (aka boolean indexing / `masking`)

In [643]:
a = np.array([33, 34, 35, 36])
a

array([33, 34, 35, 36])

In [644]:
print(a[1])  # single indexing
print(a[[2, 3, 3, 3, -1, 2, 3, -2, 0]])  # multi indexing
print(a[[2, 0, 3, -2, 0]])  # multi indexing
# review...

34
[35 36 36 36 36 35 36 35 33]
[35 33 36 35 33]


In [645]:
print(a[[True, True, False, True]])  # show show hide show

[33 34 36]


In [646]:
a >= 35

array([False, False,  True,  True])

In [647]:
a[a >= 35]

array([35, 36])

In [648]:
a[a != 35]

array([33, 34, 36])

In [649]:
a[a % 2 == 1]

array([33, 35])

In [650]:
a[a > a.mean()]

array([35, 36])

In [651]:
a[~(a > a.mean())]

array([33, 34])

In [652]:
a[(a == 33) | (a == 36)]  # `or` is for regular python, use symbol in numpy

array([33, 36])

In [653]:
a[(a <= 33) & (a == 36)]  # `and`` is for regular python, use symbol in numpy

array([], dtype=int64)

In [654]:
a[(a >= 34) & (a % 2 == 0)]  # and is for regular python, use symbol in numpyß

array([34, 36])

In [655]:
A = np.random.randint(100, size=(4, 6))  # introducing random function
A

array([[78, 80, 51, 79, 83,  3],
       [60, 16, 73, 42, 75, 62],
       [53, 33, 21, 38, 79, 92],
       [74, 80, 27, 72, 21, 93]])

In [656]:
mask = A > 30
mask

array([[ True,  True,  True,  True,  True, False],
       [ True, False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True],
       [ True,  True, False,  True, False,  True]])

In [657]:
A[mask]

array([78, 80, 51, 79, 83, 60, 73, 42, 75, 62, 53, 33, 38, 79, 92, 74, 80,
       72, 93])

In [658]:
A[A > 30]

array([78, 80, 51, 79, 83, 60, 73, 42, 75, 62, 53, 33, 38, 79, 92, 74, 80,
       72, 93])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# 🤡 Useful numpy functions

### `random`

In [683]:
ra = np.random.random(size=2)
ra

array([0.75386857, 0.64391928])

In [684]:
ra = np.random.random(size=(2, 5))
ra

array([[0.0716597 , 0.49625443, 0.08837399, 0.13664984, 0.97833305],
       [0.93196358, 0.68259957, 0.45054225, 0.85166568, 0.96188007]])

In [686]:
ra = np.random.randn(
    100, 100
)  # Return a sample (or samples) from the “standard normal” distribution.
print(ra)
print("avg:", ra.mean().round(2), "  std:", ra.std().round(2))

[[-0.30786288 -0.35747593  0.39244994 ... -1.24549871  0.59343228
  -1.29715114]
 [-3.10643073  0.5853608  -0.14831392 ... -2.32442078  1.44632622
   1.61055288]
 [-0.39445674  0.30711423 -1.56672866 ...  1.08037635 -0.18550781
  -0.01187859]
 ...
 [-1.2605474   1.34381899 -1.20006322 ...  0.46654936  1.64610308
   0.92718528]
 [-1.09947226 -0.41466461  0.29429574 ...  1.10442942 -1.21199721
  -0.19719455]
 [-0.07354239 -0.27910158 -0.87001989 ... -0.57140595  2.42661243
   1.75617004]]
avg: 0.0   std: 1.0


### `zeros`, `ones`, `empty`, `zeros_like`, `ones_like`

In [514]:
np.zeros(5)  # default float

array([0., 0., 0., 0., 0.])

In [515]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [516]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [517]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [518]:
np.ones((2, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [519]:
np.ones((3, 3)) * 3.14

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [520]:
for i in range(5):
    print(np.empty(np.random.randint(1, 5)))
    print("")

[7.29290211e-304 7.74682413e-304 7.74860419e-304]

[0.19819085 0.52639216]

[0.19819085 0.52639216]

[5.e-324 0.e+000 5.e-324 0.e+000]

[5.e-324]



In [521]:
ra = np.random.rand(2, 4)
np.ones_like(ra)  # taking shadow of ra

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [522]:
ra = np.random.rand(2, 4)
np.zeros_like(ra)  # taking shadow of ra

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### round

In [523]:
ra = np.random.rand(3, 4)
ra

array([[0.5879125 , 0.12427363, 0.74642442, 0.64311975],
       [0.76258475, 0.97515408, 0.00772403, 0.752761  ],
       [0.06138905, 0.85345089, 0.80971416, 0.21322749]])

In [524]:
ra.round(3)

array([[0.588, 0.124, 0.746, 0.643],
       [0.763, 0.975, 0.008, 0.753],
       [0.061, 0.853, 0.81 , 0.213]])

### stack or concat

In [525]:
ra1 = np.random.rand(3, 4).round(3)
print(ra1)

print("-" * 30)
ra2 = np.random.rand(3, 2).round(2)
print(ra2)

[[0.191 0.143 0.596 0.87 ]
 [0.823 0.982 0.122 0.468]
 [0.313 0.705 0.157 0.168]]
------------------------------
[[0.59 0.42]
 [0.49 0.25]
 [0.15 0.7 ]]


In [526]:
ra3 = np.hstack([ra1, ra2])
ra3

array([[0.191, 0.143, 0.596, 0.87 , 0.59 , 0.42 ],
       [0.823, 0.982, 0.122, 0.468, 0.49 , 0.25 ],
       [0.313, 0.705, 0.157, 0.168, 0.15 , 0.7  ]])

In [527]:
ra3 = np.hstack([ra2, ra1])  # swap left and right
ra3

array([[0.59 , 0.42 , 0.191, 0.143, 0.596, 0.87 ],
       [0.49 , 0.25 , 0.823, 0.982, 0.122, 0.468],
       [0.15 , 0.7  , 0.313, 0.705, 0.157, 0.168]])

In [528]:
ra4 = np.vstack([ra3, np.zeros(6)])
ra4

array([[0.59 , 0.42 , 0.191, 0.143, 0.596, 0.87 ],
       [0.49 , 0.25 , 0.823, 0.982, 0.122, 0.468],
       [0.15 , 0.7  , 0.313, 0.705, 0.157, 0.168],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   ]])

In [529]:
ra4 = np.vstack([np.zeros(6), ra3])  # swap top and bottom
ra4

array([[0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.59 , 0.42 , 0.191, 0.143, 0.596, 0.87 ],
       [0.49 , 0.25 , 0.823, 0.982, 0.122, 0.468],
       [0.15 , 0.7  , 0.313, 0.705, 0.157, 0.168]])

In [530]:
ra5 = np.hstack([ra4, np.ones((4, 1))])
ra5

array([[0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   ],
       [0.59 , 0.42 , 0.191, 0.143, 0.596, 0.87 , 1.   ],
       [0.49 , 0.25 , 0.823, 0.982, 0.122, 0.468, 1.   ],
       [0.15 , 0.7  , 0.313, 0.705, 0.157, 0.168, 1.   ]])

In [531]:
np.concatenate([ra5, ra5, ra5])

array([[0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   ],
       [0.59 , 0.42 , 0.191, 0.143, 0.596, 0.87 , 1.   ],
       [0.49 , 0.25 , 0.823, 0.982, 0.122, 0.468, 1.   ],
       [0.15 , 0.7  , 0.313, 0.705, 0.157, 0.168, 1.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   ],
       [0.59 , 0.42 , 0.191, 0.143, 0.596, 0.87 , 1.   ],
       [0.49 , 0.25 , 0.823, 0.982, 0.122, 0.468, 1.   ],
       [0.15 , 0.7  , 0.313, 0.705, 0.157, 0.168, 1.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.   ],
       [0.59 , 0.42 , 0.191, 0.143, 0.596, 0.87 , 1.   ],
       [0.49 , 0.25 , 0.823, 0.982, 0.122, 0.468, 1.   ],
       [0.15 , 0.7  , 0.313, 0.705, 0.157, 0.168, 1.   ]])

### cumsum, cumprod, diff

In [664]:
a1 = np.cumsum([1, 2, 3, 4, 5])
a1

array([ 1,  3,  6, 10, 15])

In [665]:
a2 = np.cumsum(range(1, 10))  # fibonacci
a2

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [666]:
a3 = np.cumprod(range(2, 10))  # fibonacci
a3

array([     2,      6,     24,    120,    720,   5040,  40320, 362880])

In [667]:
print(np.diff(a1))
print(np.diff(a2))
print(np.diff(a3))

[2 3 4 5]
[2 3 4 5 6 7 8 9]
[     4     18     96    600   4320  35280 322560]
