![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<div style="background-color: white; padding: 10px; display: inline-block;">
    <img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />
</div>

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [293]:
import numpy as np

## Basic Numpy Arrays

type

In [294]:
lst = [11, 12, 13]
print(type(lst))
lst

<class 'list'>


[11, 12, 13]

In [295]:
arr = np.array(lst)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([11, 12, 13])

Note: Printing and formatting in `Jupyter Notebook` or `Google Colab` may behave differently compared to standard Python scripts.

In `Jupyter/Colab`, the output of the last executed expression in a cell is automatically displayed, even if you don’t explicitly use print().

This can sometimes lead to confusion, especially when you're comparing outputs or expecting consistent behavior across different environments.

To ensure consistent output and avoid ambiguity, it's recommended to use `print()` explicitly when you want to display results.

In [296]:
a = np.array([1, 2, 3, 4])
print("print using print():")
print(a)

a

print using print():
[1 2 3 4]


array([1, 2, 3, 4])

In [297]:
b = np.array([0, 0.5, 1, 1.5, 2])
print("print using print():")
print(b)

b

print using print():
[0.  0.5 1.  1.5 2. ]


array([0. , 0.5, 1. , 1.5, 2. ])

indexing (also aware display style)

In [298]:
for x in [a[0], a[1], a[2], a[1], b[1], b[0], b[2]]:
    print(x)

1
2
3
2
0.5
0.0
1.0


In [299]:
a[0], a[1], a[2], a[1], b[1], b[0], b[2]

(np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(2),
 np.float64(0.5),
 np.float64(0.0),
 np.float64(1.0))

more indexing 

In [300]:
a = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(a)
print(a[-1:3])
print(a[-9:5])
print(a[1:-1])
print(a[::2])
print(a[::3])
print(a[::-2])
print(a[::-1])

[11 12 13 14 15 16 17 18 19 20]
[]
[12 13 14 15]
[12 13 14 15 16 17 18 19]
[11 13 15 17 19]
[11 14 17 20]
[20 18 16 14 12]
[20 19 18 17 16 15 14 13 12 11]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Array Data Types

In [301]:
a = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [302]:
type(a)

numpy.ndarray

In [303]:
a.dtype

dtype('int64')

In [304]:
b = np.array([0, 0.5, 1, 1.5, 2])
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [305]:
b.dtype

dtype('float64')

In [306]:
lst = np.array([3.14, 12.9, 13.0, 14.1], dtype=int)
lst

array([ 3, 12, 13, 14])

In [307]:
print(np.array([11, 12, 13, 14]))  # default by integer
print(np.array([11, 12, 13, 14], dtype=int))
print(np.array([11, 12, 13, 14], dtype=float))

[11 12 13 14]
[11 12 13 14]
[11. 12. 13. 14.]


In [308]:
c = np.array(["a", "b", "c"])
print(c.dtype)  # `Ùnicode String``

<U1


In [309]:
d = np.array(["a", "b", "c", 11, 12, 13])
print(d.dtype)  # `Ùnicode String``
d

<U21


array(['a', 'b', 'c', '11', '12', '13'], dtype='<U21')

In [310]:
e = np.array([True, False, True])
print(e.dtype)
e

bool


array([ True, False,  True])

To know more about data type see this [document](https://numpy.org/devdocs/reference/arrays.dtypes.html)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Array Dimensions, shapes, size etc

In [311]:
lst = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
lst

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

In [312]:
A = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### reshape

In [313]:
# you can create above array more easily using `reshape``

A = np.array(range(12)).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [314]:
print("num of rows & cols:", A.shape)
print("dimension:", A.ndim)
print("num of elems:", A.size)

num of rows & cols: (3, 4)
dimension: 2
num of elems: 12


In [315]:
B = np.array(range(40))
B = B.reshape(2, 4, 5)
B

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [316]:
print(B.dtype)
print(B.shape)
print(B.ndim)
print(B.size)

int64
(2, 4, 5)
3
40


In [317]:
print(B.shape[0])  # row count
print(B.shape[1])  # col count

2
4


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

### row indexing

In [318]:
# Square matrix
A = np.array(range(40)).reshape(5, 8)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [319]:
A[2]  # 3rd row NOT 3rd elem

array([16, 17, 18, 19, 20, 21, 22, 23])

In [320]:
print(A[0:-1])
print("")

print(A[1:])
print("")

print(A[:2])
print("")

print(A[1:-1])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]

[[ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

[[ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [321]:
A[:, [3, 1, 2, 3]]  # multi indexing columns

array([[ 3,  1,  2,  3],
       [11,  9, 10, 11],
       [19, 17, 18, 19],
       [27, 25, 26, 27],
       [35, 33, 34, 35]])

### row & col indexing using comma

In [322]:
A[:, :2]

array([[ 0,  1],
       [ 8,  9],
       [16, 17],
       [24, 25],
       [32, 33]])

In [323]:
A[:2, :2]

array([[0, 1],
       [8, 9]])

In [324]:
A[:2, 2:]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15]])

### chained indexing vs comma indexing

In [325]:
print(A[1][0])  # chainned indexing
print(A[1, 0])  # comma indexing

# you WILL SEE DIFF SOON!

8
8


In [326]:
print(A[1][:])  # chainned indexing
print(A[1, :])  # comma indexing

# you WILL SEE DIFF SOON!

[ 8  9 10 11 12 13 14 15]
[ 8  9 10 11 12 13 14 15]


In [327]:
print(A[:][2])  # chainned indexing
print(A[:, 2])  # comma indexing

# SEE DIFFERANCE?

[16 17 18 19 20 21 22 23]
[ 2 10 18 26 34]


### introducing broadcasting

In [328]:
A  # re-check how A looks like

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [329]:
lst = np.array([11, 12, 13, 14])
lst - 100

array([-89, -88, -87, -86])

In [330]:
A[1] = np.array([10, 10, 10, 10])
A
# this is NOT broadcasting. we are assigning list to be fit same sie

ValueError: could not broadcast input array from shape (4,) into shape (8,)

In [331]:
A = np.array(range(20)).reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [332]:
A[2] = 99
A
# this IS broadcasting! SINGLE INTEGER is propagating to entire row

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [99, 99, 99, 99, 99],
       [15, 16, 17, 18, 19]])

In [333]:
# broadcasting is NOT working in regular python
lst = [[11, 12, 13], [10, 10, 10], [17, 18, 19]]

lst[2] = 99

lst

[[11, 12, 13], [10, 10, 10], 99]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

### 1D array stat

In [334]:
a = np.array([31, 32, 33, 34])
a

array([31, 32, 33, 34])

In [335]:
a.sum()

np.int64(130)

In [336]:
np.sum(a)

np.int64(130)

In [337]:
a.mean()

np.float64(32.5)

In [338]:
np.mean(a)  # also works same as above

np.float64(32.5)

In [339]:
a.var()

np.float64(1.25)

In [340]:
np.sqrt(a.var())

np.float64(1.118033988749895)

In [341]:
a.std()  # you now stadard deviation is square root of variance

np.float64(1.118033988749895)

### 2D array stat (introducing axis)

In [342]:
A = np.array(range(31, 35)).reshape(2, 2)
A

array([[31, 32],
       [33, 34]])

In [343]:
A.mean(axis=1)

array([31.5, 33.5])

In [344]:
A.sum(axis=0)

array([64, 66])

In [345]:
A.sum(axis=0)  # by row (=within row X), vertically

array([64, 66])

In [346]:
A.sum(axis=1)  # by col (=within col X), horizontally

array([63, 67])

In [347]:
A = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

In [348]:
A.sum(), A.mean(), A.var(), A.std()

(np.int64(135),
 np.float64(15.0),
 np.float64(6.666666666666667),
 np.float64(2.581988897471611))

In [349]:
A.sum(axis=0), A.sum(axis=1)

(array([42, 45, 48]), array([36, 45, 54]))

In [350]:
A.mean(axis=0), A.mean(axis=1)

(array([14., 15., 16.]), array([12., 15., 18.]))

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)



## Arange & Linspace

### Arange(lib) vs Range(regular python)

In [351]:
print(list(range(10)))
print(list(range(11, 20)))
print(list(range(11, 20, 3)))
print(list(range(20, 11, -3)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 12, 13, 14, 15, 16, 17, 18, 19]
[11, 14, 17]
[20, 17, 14]


In [352]:
np.arange(1, 2, 0.05)

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95])

In [353]:
print(np.arange(10))
print(np.arange(11, 20))
print(np.arange(11, 20, 3))

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[11 14 17]


In [354]:
print(np.arange(11, 20, 1.25))  # try if it works in regular python

[11.   12.25 13.5  14.75 16.   17.25 18.5  19.75]


### linspace

In [355]:
np.arange(0, 1, 0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [356]:
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [357]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [358]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## Vectorized operations (w/ broadcasting review)

In [359]:
np.array([11, 12, 13, 14]) * 100

array([1100, 1200, 1300, 1400])

In [360]:
np.arange(11, 15) - 99

array([-88, -87, -86, -85])

In [361]:
lst = [11, 12, 13, 14] + 100
# error, "lst + integer" not working in python

TypeError: can only concatenate list (not "int") to list

In [ ]:
lst = [11, 12, 13, 14]
# you need to use for loop (this is much longer process compared to numpy)
[i + 100 for i in lst]

[111, 112, 113, 114]

In [ ]:
a = [100, 101, 102, 103]
b = [3, 4, 5, 6]

In [ ]:
a + b

[100, 101, 102, 103, 3, 4, 5, 6]

In [ ]:
np.array(a) + np.array(b)

array([103, 105, 107, 109])

In [ ]:
# a * b # error!

In [ ]:
np.array(a) * np.array(b)

array([300, 404, 510, 618])

## Logical Indexing

In [ ]:
a = np.array([33, 34, 35, 36])
a

array([33, 34, 35, 36])

In [ ]:
print(a[1])  # single indexing
print(a[[2, 3, 3, 3, -1, 2, 3, -2, 0]])  # multi indexing
print(a[[2, 0, 3, -2, 0]])  # multi indexing
print(a[[True, True, False, True]])  # logical indexing

34
[35 36 36 36 36 35 36 35 33]
[35 33 36 35 33]
[33 34 36]


In [ ]:
a >= 35

array([False, False,  True,  True])

In [ ]:
a[a >= 35]

array([35, 36])

In [ ]:
a[a % 2 == 0]

array([34, 36])

In [ ]:
a[a > a.mean()]

array([35, 36])

In [ ]:
a[~(a > a.mean())]

array([33, 34])

In [ ]:
a[(a == 33) | (a == 36)]  # or is for regular python, use symbol in numpy

array([33, 36])

In [ ]:
a[(a <= 33) & (a == 36)]  # and is for regular python, use symbol in numpy

array([], dtype=int64)

In [ ]:
a[(a >= 34) & (a % 2 == 0)]  # and is for regular python, use symbol in numpyß

array([34, 36])

In [ ]:
A = np.random.randint(100, size=(4, 6))  # introducing random function
A

array([[51, 27, 65, 59, 79, 96],
       [52, 24, 59, 92, 71, 57],
       [ 5, 85, 72, 92, 49, 74],
       [93, 87,  9, 10, 93, 28]])

In [ ]:
A[
    np.array(
        [
            [True, False, True, False, True, False],
            [False, True, False, True, True, False],
            [True, False, True, True, True, False],
            [True, False, True, False, False, True],
        ]
    )
]
# once logical indexing is used for 2D array. We cannot keep the shape

array([51, 65, 79, 24, 92, 71,  5, 72, 92, 49, 93,  9, 28])

In [ ]:
mask = A > 30
mask

array([[ True, False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [ True,  True, False, False,  True, False]])

In [ ]:
A[mask]

array([51, 65, 59, 79, 96, 52, 59, 92, 71, 57, 85, 72, 92, 49, 74, 93, 87,
       93])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [ ]:
A = [[1, 2], [3, 4]]
B = [[10, 20], [30, 40]]
A = np.array(A)
B = np.array(B)

In [ ]:
A + B

array([[11, 22],
       [33, 44]])

In [ ]:
A * B

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
B * A

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
A @ B  # result can be diff from A * B

array([[ 70, 100],
       [150, 220]])

In [ ]:
B @ A  # result can be diff from A * B

array([[ 70, 100],
       [150, 220]])

In [ ]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

D = np.array([[6, 5], [4, 3], [2, 1]])

In [ ]:
C.dot(D)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
C @ D  # same as C.dot(D)

array([[20, 14],
       [56, 41],
       [92, 68]])

### transpose

In [ ]:
C.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
D.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
D @ C  # error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
D.T @ C

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

In [ ]:
import sys

### Int, floats

In [ ]:
# remember we import sys module
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**99)

68

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

Lists are even larger

In [ ]:
# A one-element list
print(sys.getsizeof([1]))
print(sys.getsizeof([1, 2, 3, 4]))

64
88


In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [ ]:
l = list(range(1000000))
a = np.arange(1000000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 1.83 ms, sys: 2.23 ms, total: 4.06 ms
Wall time: 2.78 ms


333332833333500000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 305 ms, sys: 16.4 ms, total: 322 ms
Wall time: 321 ms


333332833333500000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

`random` 

In [ ]:
ra = np.random.random(size=2)
ra

array([0.71478833, 0.86032725])

In [ ]:
ra = np.random.normal(size=2)
ra

array([-0.44324428, -1.02727548])

In [ ]:
ra = np.random.rand(2, 4)
ra

array([[0.9895843 , 0.89121794, 0.35941467, 0.20615986],
       [0.84238982, 0.16902483, 0.49874971, 0.25918184]])

In [ ]:
ra = np.random.randn(
    100, 100
)  # Return a sample (or samples) from the “standard normal” distribution.
print(ra)
print("avg:", ra.mean().round(2), "  std:", ra.std().round(2))

[[ 0.48612894 -1.04400509 -1.40641645 ...  0.34520384 -0.18899413
   1.73516893]
 [-0.47094705 -0.08451515 -0.57197409 ...  0.76662248 -1.65146258
  -1.04310813]
 [ 0.86841155 -0.58263025  1.79034453 ...  0.34216261 -1.02197446
   0.89326353]
 ...
 [-1.0443312   0.24548079  0.95951075 ...  0.21298886 -1.29126276
  -1.76435457]
 [-0.87233576  1.12208252 -2.55040666 ... -0.51984534 -1.11200374
  -0.56672076]
 [ 1.0625598  -2.0873782   0.55717693 ...  1.0973261  -0.80111329
   1.14261325]]
avg: 0.01   std: 1.0


`reshape`

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(12).reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

`zeros`, `ones`, `empty`

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3, 3)) * 1234

array([[1234., 1234., 1234.],
       [1234., 1234., 1234.],
       [1234., 1234., 1234.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2, 2, 2))

array([[[0.9895843 , 0.89121794],
        [0.35941467, 0.20615986]],

       [[0.84238982, 0.16902483],
        [0.49874971, 0.25918184]]])

In [ ]:
ra = np.random.rand(2, 4)
np.ones_like(ra)  # taking shadow of ra

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
ra = np.random.rand(2, 4)
np.zeros_like(ra)  # taking shadow of ra

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

`identity` & `eye`

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])