In [113]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print("numpy version:", np.__version__)

numpy version: 2.3.1


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Creation

---
create empty numpy array

In [4]:
# your answer

---
Given the X python list convert it to an Y numpy array. Then print it with its type.

In [5]:
X = [[11, 12, 13], [14, 15, 16]]  # given
print(X, type(X))  # given example

[[11, 12, 13], [14, 15, 16]] <class 'list'>


In [6]:
# your answer

---
Given the `X` numpy array
- make a copy and store it as `Y`
- then print itself and its id
- will `X` and `Y` have identical id?

In [7]:
# given info
X = np.array([5, 2, 3], dtype=int)
print(X, id(X))

[5 2 3] 4728049744


In [8]:
# your answer

---
Print a numpy array with `integers` from 1 to 10 `using range function`

In [9]:
# your answer

---
Print a numpy array with `integers` from 1 to 10 `using linspace function`

In [10]:
# your answer

---
Print a numpy array with the `odd integers` between 1 to 10

In [11]:
# your answer

---
Print a numpy array with `integers` from 10 to 1, in descending order.

In [12]:
# your answer

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Attributes Basic


---
Given numpy array `arr`, show its
- 1. dimension - which should be 2
- 2. element counts - which should be 6
- 3. row count
- 4. column count
- 5. item size of its data type (it is integer, so it must show 8-bit)

In [13]:
# given arr
X = [[11, 12, 13], [14, 15, 16]]
arr = np.array(X)
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [14]:
# your answer

---
Given numpy array `arr` is currently 2 by 3. Let's reshape this to be 3 by 2
- do not save or overwrite onto original arr, just show the temp outcome

In [15]:
# given arr
X = [[11, 12, 13], [14, 15, 16]]
arr = np.array(X)
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [16]:
# your answer

---
Given numpy array `arr` is currently 2 by 3. Let's reshape this to be 6 by 1
- do not save or overwrite onto original arr, just show the temp outcome

In [17]:
# given arr
X = [[11, 12, 13], [14, 15, 16]]
arr = np.array(X)
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [18]:
# your answer

---
Given 1D numpy array X(with large size), Let's reshape this to be 2D array have 4 rows

In [19]:
X = np.arange(1, 234125)  # Given

In [20]:
# your answer

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Indexation


---
Given the 1D X numpy array, show it's first element

In [21]:
X = np.array(["A", "B", "C", "D", "E"])  # GIVEN

In [22]:
# your answer

---
Given the X numpy array, show it's last element

In [23]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [24]:
# your answer

---
Given the X numpy array, show it's first three elements

In [25]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [26]:
# your answer

---
Given the X numpy array, show all middle elements

In [27]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [28]:
# your answer

---
Given the X numpy array, show the elements in reverse position

In [29]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [30]:
# your answer

---
Given the X numpy array, show the elements in an odd position, starting from 2nd element

In [31]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [32]:
# your answer

---
Given the X numpy matrix, show the first row

In [33]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
# your answer

---
Given the X numpy matrix, show the 2nd from last row

In [35]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
# your answer

---
Given the X numpy matrix, show the 3rd element on 2nd row
- additional question. will chained-expression work here?

In [37]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
# your answer

---
Given the X numpy matrix, show the middle row's middle elements
- additional question. will chained-expression work here?

In [39]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
# your answer

---
Given the X numpy matrix, show the first two elements on the first two rows
- additional question. will chained-expression work here?

In [41]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
# your answer

---
Given the X numpy matrix, show the last two elements on the last two rows
- additional question. will chained-expression work here?

In [43]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
# your answer

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Manipulation


---
Create a float numpy array using the given integer list

In [45]:
X = [-5, -3, 0, 10, 40]  # given

In [46]:
# your answer

---
Convert given float numpy array to integer numpy array to drop all decimals

In [47]:
X = np.array([1.1, 2.2, 3.3])  # given

In [48]:
# your answer

---
Order (sort) the given numpy array using basic python function
- will it overwrite onto X?

In [49]:
X = np.array([0, 10, -5, 40, -3])
X

array([ 0, 10, -5, 40, -3])

In [50]:
# your answer

---
Order (sort) the given numpy array using numpy function
- will it overwrite onto X?

In [51]:
X = np.array([0, 10, -5, 40, -3])
X

array([ 0, 10, -5, 40, -3])

In [52]:
# your answer

---
Given the X numpy array, set the fifth element equal to 39

In [53]:
X = np.zeros(10)  # given
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
# your answer

---
Given the X numpy matrix, change the last row with all `1`

In [55]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
# your answer

---
Given the X numpy matrix, change the last item on the last row with `0`

In [57]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
# your answer

---
Given the X numpy matrix, add 5 to every element

In [59]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
# your answer

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


---
Given the X numpy array, make a mask showing negative elements
- just show boolean array

In [61]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [62]:
# your answer

---
Given the X numpy array, get the negative elements
- you can utilize the mask you just made

In [63]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [64]:
# your answer

---
Given the X numpy array, get numbers higher than 5

In [65]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [66]:
# your answer

---
Given the X numpy array, get numbers higher than the elements mean

In [67]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [68]:
# your answer

---
Given the X numpy array, get numbers equal to 2 or 10

In [69]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [70]:
# your answer

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

---
Given the X numpy array, show the sum of its elements

In [71]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])  # given
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [72]:
# your answer

---
Given the X numpy array, show the average value of its elements

In [73]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])  # given
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [74]:
# your answer

---
Given the X numpy matrix, show the sum of its (within) columns (adding horizontaliy)

In [75]:
# Given
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [76]:
# your answer

---
Given the X numpy matrix, show the mean value of its rows

In [77]:
# Given
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
# your answer

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Common Numpy Function(zeros, zeros_like, any, all etc)


### logic functions

---
Given the X numpy array, return True if none of its elements is zero

In [114]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [80]:
# your answer

---
Given the X numpy array, return True if any of its elements is zero

In [81]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [82]:
# your answer

### array creation

---
Create a numpy array of size 10, filled with zeros.

In [83]:
# your answer

---
Create a numpy array with values ranging from 10 to 49

In [84]:
# your answer

---
Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [85]:
# your answer

---
Create a numpy matrix of 2*2 integers, filled with ones.

In [86]:
# your answer

---
Create a numpy matrix of 3*2 float numbers, filled with ones.

In [87]:
# your answer

---
Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [88]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)  # given

In [89]:
# your answer

---
Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [90]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)  # given

In [91]:
# your answer

---
Create a numpy matrix of 4*4 integers, filled with fives.

In [92]:
# your answer

### linear algebra

---
Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [93]:
# your answer

### random number

---
Create a numpy array, filled with 3 random integer values between 0 and 9.

In [94]:
# your answer

---
Create a 3\*3\*3 numpy matrix, filled with random float values.

In [95]:
# your answer

# Word Problems

---
### 1

You are given a list of integers representing test scores. Use NumPy to calculate how many scores are above the average.

🔢 Input  
- A single line of space-separated integers (0 ≤ score ≤ 100).


✅ Output  
- Print the number of scores above the average.

📌 Example
`50 80 90 60 70` -> `2`


In [96]:
def f1(s):
    lst = list(map(int, s.split()))
    arr = np.array(lst)
    arr2 = arr[arr > arr.mean()]  # logcial indexing (aka boolean indexing)
    return len(arr2)


f1("50 80 90 60 70")

2

---
### 2
You are given a list of integers. Replace all the odd numbers with -1 using NumPy.

🔢 Input  
- A single line of space-separated integers.

✅ Output  
- Print the modified array as a NumPy array.

📌 Example
`1 2 3 4 5` -> `[-1  2 -1  4 -1]`


In [97]:
def f2(s):
    lst = list(map(int, s.split()))
    arr = np.array(lst)
    arr[arr % 2 == 1] = -1
    return arr


ans = f2("1 2 3 4 5")
print(ans)

[-1  2 -1  4 -1]


---
### 3
You are given a list of numbers representing a matrix with 3 rows and 4 columns (12 numbers). Convert it to a 2D NumPy array and calculate the sum of each row.

🔢 Input  
- A single line of 12 space-separated integers.

✅ Output  
- Print the row sums as a 1D NumPy array.

📌 Example
- `1 2 3 4 5 6 7 8 9 10 11 12` -> `[10 26 42]`




In [98]:
def f3(s):
    lst = list(map(int, s.split()))
    arr = np.array(lst).reshape(3, 4)
    print(arr.sum(axis=1))


f3("1 2 3 4 5 6 7 8 9 10 11 12")

[10 26 42]


---
### 4

Jeyoung did poorly on his final exams and decided to manipulate his scores before showing them to his parents. He chose the highest score among all his subjects (let's call it M), and converted every score using the formula `(score / M) * 100`. For example, if the highest score is 70 and a subject score is 50, it becomes `(50 / 70) * 100 = 71.43`. Write a function that takes a list of space-separated, non-negative integers (at least one greater than 0, and all ≤ 100), applies this conversion to each score, and prints the new average. The answer is considered correct if the absolute or relative error is less than 10⁻².

🔢 input:
- A single line of space-separated non-negative integers, each representing a score.
- Each score is ≤ 100.
- There is at least one score greater than 0.

✅ output
- Print the new average score, calculated using the formula.
- Your answer is considered correct if the absolute or relative error is less than 10⁻².

📌 examples
- input: `40 80 60` -> output: `75.0`
- input: `10 20 30` -> output: `66.6667`
- input: `1 2 4 8 16` -> output: `38.75`


In [99]:
def f4(s):
    lst = list(map(int, s.split()))
    arr = np.array(lst)
    M = arr.max()
    arr = arr * (100 / M)
    print("printing here", arr.mean())


ans = f4("1 2 4 8 16")
print(ans)

printing here 38.75
None


---
### 5

You are given a list of exam scores from different students. However, the exam was considered too difficult, so the teacher decided to curve the grades. The curve rule is as follows:

1. Find the average of all the scores.
2. Add a fixed bonus(can be negative) to every score so that the **new average becomes 80**.
3. If any score exceeds 100 after the curve, **cap it at 100**.

Write a function that receives a space-separated string of scores, uses NumPy to perform the curve, and returns the list of adjusted scores and the new average. You might find `np.clip()` useful

🔢 Input:
- A single line of space-separated scores (non-negative integers ≤ 100). At least one score is below 80.

✅ Output:
- Print the adjusted scores (as a NumPy array)

📌 Example
- `90 95 100 20` -> `[93.75 98.75 100 23.75]`
- `90 95 100 60` -> `[83.75,88.75,93.75,53.75]`


In [100]:
def f5(s):
    arr = np.array(list(map(int, s.split())))
    bonus = 80 - arr.mean()
    arr = arr + bonus
    arr[arr > 100] = 100
    print(arr)


f5("90 95 100 60")

[83.75 88.75 93.75 53.75]


---
### 6

A high school teacher is analyzing the performance of 5 students in 3 subjects: Math, Physics, and English.

- Math scores: 80, 85, 78, 90, 88
- Physics scores: 59, 40, 35, 20, 100
- English scores: 75, 82, 79, 95, 91

The teacher wants to organize the data in two different ways using NumPy:
- `arr1`: Vertically stack the three lists so that each row represents a subject and each column represents a student.
- `arr2`: Horizontally stack the three lists so that each row represents a student and each column represents a subject.

❓Your Task:
Use `np.vstack()` and `np.hstack()` to generate both formats.

Print both arrays and explain which is more useful if you want to compare scores per student.

In [101]:
# Scores
math = np.array([80, 85, 78, 90, 88])
physics = np.array([59, 40, 35, 20, 100])
english = np.array([75, 82, 79, 95, 91])

In [102]:
# Vertically stacked: subjects as rows
arr1 = np.vstack([math, physics, english])
arr1

array([[ 80,  85,  78,  90,  88],
       [ 59,  40,  35,  20, 100],
       [ 75,  82,  79,  95,  91]])

In [103]:
# Horizontally stacked: students as rows
arr2 = np.hstack([math.reshape(-1, 1), physics.reshape(-1, 1), english.reshape(-1, 1)])
arr2

array([[ 80,  59,  75],
       [ 85,  40,  82],
       [ 78,  35,  79],
       [ 90,  20,  95],
       [ 88, 100,  91]])

In [104]:
# FYI you can also use concatenate
arr2 = np.concatenate(
    [math.reshape(-1, 1), physics.reshape(-1, 1), english.reshape(-1, 1)], axis=1
)
arr2

array([[ 80,  59,  75],
       [ 85,  40,  82],
       [ 78,  35,  79],
       [ 90,  20,  95],
       [ 88, 100,  91]])

In [105]:
# FYI another possible way not using hstack
arr1.T

array([[ 80,  59,  75],
       [ 85,  40,  82],
       [ 78,  35,  79],
       [ 90,  20,  95],
       [ 88, 100,  91]])

find the avearge score of each class, then concatenate onto arr1

In [106]:
# onto the arr1, add average of each student's score
avg = arr1.mean(axis=0).round(2)
np.vstack([arr1, avg])

array([[ 80.  ,  85.  ,  78.  ,  90.  ,  88.  ],
       [ 59.  ,  40.  ,  35.  ,  20.  , 100.  ],
       [ 75.  ,  82.  ,  79.  ,  95.  ,  91.  ],
       [ 71.33,  69.  ,  64.  ,  68.33,  93.  ]])

In [107]:
arr1

array([[ 80,  85,  78,  90,  88],
       [ 59,  40,  35,  20, 100],
       [ 75,  82,  79,  95,  91]])

In [108]:
avg2 = arr1.mean(axis=1).round(2)
avg2

array([84.2, 50.8, 84.4])

In [109]:
# onto the arr1, add average of each student's score
avg2 = arr1.mean(axis=1).round(2)
np.hstack([arr1, avg2.reshape(-1, 1)])

array([[ 80. ,  85. ,  78. ,  90. ,  88. ,  84.2],
       [ 59. ,  40. ,  35. ,  20. , 100. ,  50.8],
       [ 75. ,  82. ,  79. ,  95. ,  91. ,  84.4]])

In [110]:
arr3 = np.hstack([arr1, avg2.reshape(-1, 1)])
arr3

array([[ 80. ,  85. ,  78. ,  90. ,  88. ,  84.2],
       [ 59. ,  40. ,  35. ,  20. , 100. ,  50.8],
       [ 75. ,  82. ,  79. ,  95. ,  91. ,  84.4]])

In [111]:
arr4 = np.vstack([arr3, arr3.mean(axis=0).round(2)])
arr4

array([[ 80.  ,  85.  ,  78.  ,  90.  ,  88.  ,  84.2 ],
       [ 59.  ,  40.  ,  35.  ,  20.  , 100.  ,  50.8 ],
       [ 75.  ,  82.  ,  79.  ,  95.  ,  91.  ,  84.4 ],
       [ 71.33,  69.  ,  64.  ,  68.33,  93.  ,  73.13]])

In [ ]:
arr4[-1, -1] = np.nan
arr4

array([[ 80.  ,  85.  ,  78.  ,  90.  ,  88.  ,  84.2 ],
       [ 59.  ,  40.  ,  35.  ,  20.  , 100.  ,  50.8 ],
       [ 75.  ,  82.  ,  79.  ,  95.  ,  91.  ,  84.4 ],
       [ 71.33,  69.  ,  64.  ,  68.33,  93.  ,    nan]])

why do you think we need to replace bottom right corner to be nan?