![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print("numpy version:", np.__version__)

numpy version: 1.24.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Creation

---
create empty numpy array

In [2]:
# your answer

array([], dtype=float64)

---
Given the X python list convert it to an Y numpy array. Then print it with its type.

In [4]:
X = [[11, 12, 13], [14, 15, 16]]  # given
print(X, type(X))  # given example

[[11, 12, 13], [14, 15, 16]] <class 'list'>


In [5]:
# your answer

[[11 12 13]
 [14 15 16]] <class 'numpy.ndarray'>


---
Given the `X` numpy array
- make a copy and store it as `Y`
- then print itself and its id
- will `X` and `Y` have identical id?

In [7]:
# given info
X = np.array([5, 2, 3], dtype=int)
print(X, id(X))

[5 2 3] 140516976796368


In [8]:
# your answer

[5 2 3] 140516439521584


---
Print a numpy array with `integers` from 1 to 10 `using range function`

In [10]:
# your answer

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---
Print a numpy array with `integers` from 1 to 10 `using linspace function`

In [12]:
# your answer

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---
Print a numpy array with the `odd integers` between 1 to 10

In [14]:
# your answer

array([1, 3, 5, 7, 9])

---
Print a numpy array with `integers` from 10 to 1, in descending order.

In [16]:
# your answer

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Attributes Basic


---
Given numpy array `arr`, show its
- 1. dimension - which should be 2
- 2. element counts - which should be 6
- 3. row count
- 4. column count
- 5. item size of its data type (it is integer, so it must show 8-bit)

In [18]:
# given arr
X = [[11, 12, 13], [14, 15, 16]]
arr = np.array(X)
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [19]:
# your answer

2
6
2
3
8


---
Given numpy array `arr` is currently 2 by 3. Let's reshape this to be 3 by 2
- do not save or overwrite onto original arr, just show the temp outcome

In [21]:
# given arr
X = [[11, 12, 13], [14, 15, 16]]
arr = np.array(X)
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [22]:
# your answer

array([[11, 12],
       [13, 14],
       [15, 16]])

---
Given numpy array `arr` is currently 2 by 3. Let's reshape this to be 6 by 1
- do not save or overwrite onto original arr, just show the temp outcome

In [24]:
# given arr
X = [[11, 12, 13], [14, 15, 16]]
arr = np.array(X)
arr

array([[11, 12, 13],
       [14, 15, 16]])

In [25]:
# your answer

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16]])

---
Given 1D numpy array X(with large size), Let's reshape this to be 2D array have 4 rows

In [27]:
X = np.arange(1, 234125)  # Given

In [28]:
# your answer

array([[     1,      2,      3, ...,  58529,  58530,  58531],
       [ 58532,  58533,  58534, ..., 117060, 117061, 117062],
       [117063, 117064, 117065, ..., 175591, 175592, 175593],
       [175594, 175595, 175596, ..., 234122, 234123, 234124]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Indexation


---
Given the 1D X numpy array, show it's first element

In [30]:
X = np.array(["A", "B", "C", "D", "E"])  # GIVEN

In [31]:
# your answer

'A'

---
Given the X numpy array, show it's last element

In [33]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [34]:
# your answer

'H'

---
Given the X numpy array, show it's first three elements

In [36]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [37]:
# your answer

array(['A', 'B', 'C'], dtype='<U1')

---
Given the X numpy array, show all middle elements

In [39]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [40]:
# your answer

array(['B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1')

---
Given the X numpy array, show the elements in reverse position

In [42]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [43]:
# your answer

array(['H', 'G', 'F', 'E', 'D', 'C', 'B', 'A'], dtype='<U1')

---
Given the X numpy array, show the elements in an odd position, starting from 2nd element

In [45]:
X = np.array(["A", "B", "C", "D", "E", "F", "G", "H"])  # Given

In [46]:
# your answer

array(['B', 'D', 'F', 'H'], dtype='<U1')

---
Given the X numpy matrix, show the first row

In [48]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
# your answer

array([1, 2, 3, 4])

---
Given the X numpy matrix, show the 2nd from last row

In [51]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
# your answer

array([ 9, 10, 11, 12])

---
Given the X numpy matrix, show the 3rd element on 2nd row
- additional question. will chained-expression work here?

In [54]:
# GIVEN
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
# your answer

7
7


---
Given the X numpy matrix, show the middle row's middle elements
- additional question. will chained-expression work here?

In [57]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
# your answer

array([[ 6,  7],
       [10, 11]])

---
Given the X numpy matrix, show the first two elements on the first two rows
- additional question. will chained-expression work here?

In [61]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
# your answer

array([[1, 2],
       [5, 6]])

---
Given the X numpy matrix, show the last two elements on the last two rows
- additional question. will chained-expression work here?

In [64]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
# your answer

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Manipulation


---
Create a float numpy array using the given integer list

In [67]:
X = [-5, -3, 0, 10, 40]  # given

In [68]:
# your answer

array([-5., -3.,  0., 10., 40.])

---
Convert given float numpy array to integer numpy array to drop all decimals

In [70]:
X = np.array([1.1, 2.2, 3.3])  # given

In [71]:
# your answer

array([1, 2, 3])

---
Order (sort) the given numpy array using basic python function
- will it overwrite onto X?

In [73]:
X = np.array([0, 10, -5, 40, -3])
X

array([ 0, 10, -5, 40, -3])

In [74]:
# your answer

array([-5, -3,  0, 10, 40])

---
Order (sort) the given numpy array using numpy function
- will it overwrite onto X?

In [76]:
X = np.array([0, 10, -5, 40, -3])
X

array([ 0, 10, -5, 40, -3])

In [77]:
# your answer

array([-5, -3,  0, 10, 40])

array([ 0, 10, -5, 40, -3])

---
Given the X numpy array, set the fifth element equal to 39

In [80]:
X = np.zeros(10)  # given
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
# your answer

array([ 0.,  0.,  0.,  0., 39.,  0.,  0.,  0.,  0.,  0.])

---
Given the X numpy matrix, change the last row with all `1`

In [83]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [84]:
# your answer

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

---
Given the X numpy matrix, change the last item on the last row with `0`

In [86]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [87]:
# your answer

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

---
Given the X numpy matrix, add 5 to every element

In [89]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])  # Given
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
# your answer

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


---
Given the X numpy array, make a mask showing negative elements
- just show boolean array

In [92]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [93]:
# your answer

array([ True, False, False,  True, False, False, False, False,  True,
       False])

---
Given the X numpy array, get the negative elements
- you can utilize the mask you just made

In [95]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [96]:
# your answer

array([-1, -4, -9])

---
Given the X numpy array, get numbers higher than 5

In [98]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [99]:
# your answer

array([ 6, 10])

---
Given the X numpy array, get numbers higher than the elements mean

In [101]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [102]:
# your answer

array([ 2,  5,  6, 10])

---
Given the X numpy array, get numbers equal to 2 or 10

In [104]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])  # Given
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [105]:
# your answer

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

---
Given the X numpy array, show the sum of its elements

In [107]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])  # given
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [108]:
# your answer

43
43


---
Given the X numpy array, show the average value of its elements

In [110]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])  # given
X

array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [111]:
# your answer

4.777777777777778
4.777777777777778


---
Given the X numpy matrix, show the sum of its (within) columns (adding horizontaliy)

In [113]:
# Given
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [114]:
# your answer

array([28, 32, 36, 40])

---
Given the X numpy matrix, show the mean value of its rows

In [116]:
# Given
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [117]:
# your answer

array([ 2.5,  6.5, 10.5, 14.5])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## More Numpy Function(zeros, zeros_like, any, all etc)


### logic functions

---
Given the X numpy array, return True if none of its elements is zero

In [119]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [120]:
# your answer

False

---
Given the X numpy array, return True if any of its elements is zero

In [122]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X

array([-1,  2,  0, -4,  5,  6,  0,  0, -9, 10])

In [123]:
# your answer

False

### array creation

---
Create a numpy array of size 10, filled with zeros.

In [125]:
# your answer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---
Create a numpy array with values ranging from 10 to 49

In [127]:
# your answer

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

---
Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [129]:
# your answer

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

---
Create a numpy matrix of 2*2 integers, filled with ones.

In [131]:
# your answer

array([[1, 1],
       [1, 1]])

---
Create a numpy matrix of 3*2 float numbers, filled with ones.

In [133]:
# your answer

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

---
Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [135]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)  # given

In [136]:
# your answer

array([[1, 1, 1],
       [1, 1, 1]])

---
Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [138]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)  # given

In [139]:
# your answer

array([[0, 0, 0],
       [0, 0, 0]])

---
Create a numpy matrix of 4*4 integers, filled with fives.

In [141]:
# your answer

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### linear algebra

---
Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [143]:
# your answer

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random number

---
Create a numpy array, filled with 3 random integer values between 0 and 9.

In [145]:
# your answer

array([7, 7, 6])

---
Create a 3\*3\*3 numpy matrix, filled with random float values.

In [147]:
# your answer

array([[[-0.16182618,  1.5663729 ,  1.04596085],
        [-1.83652378,  0.45793726,  0.54311143],
        [ 0.84027795, -1.4882627 , -2.73334138]],

       [[-0.49536088, -0.27389104, -0.05232908],
        [ 0.79080269,  0.77733099,  1.14444544],
        [-1.93621678,  1.15241245,  0.23815859]],

       [[-0.20668043, -0.78323185, -0.07429321],
        [-0.69929113,  1.06697175, -0.80283181],
        [ 0.69307696,  0.36433569,  1.12855343]]])

---
Show the memory size of the given Z numpy matrix `np.zeros((10,10))`

In [149]:
# your answer

800 bytes
