# Splitting the Data into Training and Test Sets

* **Training Data (Train data)**: The subset of the dataset used to train the model.
* **Test Data (Test data)**: The subset of the dataset used to evaluate the performance of the trained model.

The data is usually split into these sets to prevent overfitting and to ensure that the model generalizes well to unseen data.


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Prepare the data

In [57]:
# In this lesson we will explore the train_test_split module
# Therefore we need no more than the module itself and NumPy
import numpy as np

In [58]:
# Let's generate a new data frame 'a' which will contain all integers from 1 to 100
# The method np.arange works like the built-in method 'range' with the difference it creates an array
a = np.arange(1, 101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [59]:
# Similarly, let's create another ndarray 'b', which will contain integers from 501 to 600
# We have intentionally picked these numbers so we can easily compare the two
# Obviously, the difference between the elements of the two arrays is 500 for any two corresponding elements
b = np.arange(501, 601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

# Split the Data

You can use the `train_test_split()` method to split data into training and testing sets.

Reference: [train_test_split documentation](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)


In [60]:
from sklearn.model_selection import train_test_split
train_test_split(a)

[array([ 81,  93,  78,  54,   4,  10,  16,  11, 100,  25,  42,  84,  44,
         88,  36,  97,  32,  95,   6,  70,  35,  80,  68,  22,  91,   3,
         20,  56,  67,  49,  57,  33,  75,  55,  50,  65,  73,  12,  21,
         61,  15,  83,  66,  17,  51,  27,  29,  90,   8,  47,  99,  34,
         72,  19,  46,  96,  28,  82,  38,  76,   2,  23,  92,  79,  77,
         39,  24,  86,  58,   7,  45,   5,  30,   1,  98]),
 array([41, 63, 26, 37, 13, 64, 14, 60, 48, 87, 31, 74, 53, 52, 62, 71, 18,
        69,  9, 40, 43, 59, 89, 85, 94])]

# Parameters of train_test_split

* **test_size**: The proportion (float) or number (int) of the dataset to be used for testing (default = 0.25).
* **train_size**: The proportion (float) or number (int) of the dataset to be used for training (default = remainder of `test_size`).
* **random_state**: The seed value for shuffling the data during splitting (can be an int or RandomState).
* **shuffle**: Whether to shuffle the data before splitting (default = True).


In [61]:
from sklearn.model_selection import train_test_split

In [62]:
a_train, a_test, b_train, b_test = train_test_split(
    a, b, test_size=0.3, random_state=365
)

# Let's check the shapes
# Basically, we are checking how does the 'test_size' work
a_train.shape, a_test.shape, b_train.shape, b_test.shape

((70,), (30,), (70,), (30,))

### What is `stratify`?

Ensures that the proportions of the specified data (usually the labels, `Y`) are maintained in the split. For example, if the label set `Y` consists of 25% 0's and 75% 1's in a binary classification task, setting `stratify=Y` will keep the same proportions (25% 0's and 75% 1's) in both the training and test sets.

🎓 Example: Engineering School Students

Let’s say we have a dataset of 100 engineering students:
- 90 male students
- 10 female students

We want to split them into train and test sets. But if we do it randomly, it’s possible the test set ends up with no female students at all, which makes it hard to test models fairly.
- try with random_seed 335

In [195]:
from sklearn.model_selection import train_test_split

# Sample data: gender of students
students = ['M'] * 90 + ['F'] * 10
labels = ['Engineering'] * 100  # just a placeholder label for all
random_seed = np.random.randint(1000)
# random_seed = 335
print("seed:", random_seed)

# Without stratify
train1, test1 = train_test_split(
    students, test_size=0.3, random_state=random_seed)
print("Without stratify:")
print("Train:", train1)
print("Test:", test1)
print("Female count:", test1.count("F"))

# With stratify
train2, test2 = train_test_split(
    students, test_size=0.3, random_state=random_seed, stratify=students)
print("\nWith stratify:")
print("Train:", train2)
print("Test:", test2)
print("Female count:", test2.count("F"))

seed: 89
Without stratify:
Train: ['M', 'M', 'M', 'F', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M']
Test: ['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M']
Female count: 2

With stratify:
Train: ['M', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M']
Test: ['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', '

### What is `random_state`?

The `random_state` parameter controls the **randomness** of the data splitting process in `train_test_split`. By setting a fixed `random_state`, you ensure that the split is reproducible—this means you will get the same training and testing datasets every time you run the code.

---

- Why is `random_state` important?

In machine learning, randomness is often involved in:
1. Splitting the dataset into training and testing sets.
2. Initializing model parameters (e.g., weights in neural networks).
3. Sampling from the data.

If you don't control the randomness (i.e., don't set `random_state`), you'll get different results each time you run the code. This can make debugging and comparing results difficult. By specifying `random_state`, you effectively set a **seed** for the random number generator, ensuring consistent and repeatable behavior.


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Practice: Splitting the Dataset

## Iris

In [63]:
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()
X = iris.data  # features
y = iris.target  # labels

In [64]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [65]:
print(X.shape, y.shape)

(150, 4) (150,)


In [66]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

print("Training features shape:", X_train.shape)
print("Test features shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Test labels shape:", y_test.shape)

Training features shape: (112, 4)
Test features shape: (38, 4)
Training labels shape: (112,)
Test labels shape: (38,)


## Wine

In this example, we will load the wine dataset and split it into training and testing sets.

In [38]:
from sklearn.datasets import load_wine

# Load the wine dataset
wine = load_wine()
X = wine.data  # Features
y = wine.target  # Labels

In [39]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3

In [40]:
print(X.shape, y.shape)

(178, 13) (178,)


In [41]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y)

print("Training features shape:", X_train.shape)
print("Test features shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Test labels shape:", y_test.shape)

Training features shape: (124, 13)
Test features shape: (54, 13)
Training labels shape: (124,)
Test labels shape: (54,)


## Brest Cancer

In [42]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
X = cancer.data
y = cancer.target
print(X.shape, y.shape)

(569, 30) (569,)


In [43]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y)

print("Training features shape:", X_train.shape)
print("Test features shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Test labels shape:", y_test.shape)

Training features shape: (512, 30)
Test features shape: (57, 30)
Training labels shape: (512,)
Test labels shape: (57,)


## Diabetes

In [44]:
from sklearn.datasets import load_diabetes

diab = load_diabetes()
X = diab.data
y = diab.target
print(X.shape, y.shape)

(442, 10) (442,)


In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

### why stratify not working here?

`stratify` is used in classification problems to maintain the class proportions in the train and test splits.  
However, the `y` in the Diabetes dataset is **continuous data (a regression target)**, meaning it does not have discrete classes (categories).  
As a result, sklearn cannot divide `y` into classes, and setting `stratify=y` causes the error mentioned above.


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)


print("Training features shape:", X_train.shape)
print("Test features shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Test labels shape:", y_test.shape)

Training features shape: (397, 10)
Test features shape: (45, 10)
Training labels shape: (397,)
Test labels shape: (45,)
