# Naive Bayes Classifier with Scikit-learn

**Naive Bayes** is a simple yet powerful classification model based on **Bayes’ Theorem**.  
It assumes that all features are **independent** of each other — hence the term *"naive"*.

Despite its simplicity, Naive Bayes often performs surprisingly well, especially in:

- Text classification (e.g., spam detection)
- Sentiment analysis
- Document categorization

---

**Bayes’ Theorem** helps calculate the probability of a class given the features:  
$$
P(\text{Class} \mid \text{Data}) = \frac{P(\text{Data} \mid \text{Class}) \cdot P(\text{Class})}{P(\text{Data})}
$$

- $P(\text{Class} \mid \text{Data})$: Posterior probability (what we want to predict)  
- $P(\text{Data} \mid \text{Class})$: Likelihood (how likely the data is given the class)  
- $P(\text{Class})$: Prior probability of the class  
- $P(\text{Data})$: Overall probability of the data (same for all classes)

---

We will now implement a Naive Bayes classifier using **Scikit-learn**.


### Classifying Whether to Play Soccer Based on Weather and Temperature

We create a dataset with 2 features and 1 label:

- **Features:**
  - `Weather` with categories:  
    0 = 'Cloudy', 1 = 'Rainy', 2 = 'Sunny'  
  - `Temperature` with categories:  
    0 = 'Cool', 1 = 'Hot', 2 = 'Mild'

- **Label:**  
  - `Play` with categories:  
    0 = 'Don’t Play', 1 = 'Play'

This simple dataset will help us understand how to build a classification model with categorical features.


In [2]:
import numpy as np

In [15]:
weather = np.array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])
temp = np.array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])
label = np.array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [16]:
features = zip(weather, temp)
features = list(features)
print(features)

[(np.int64(2), np.int64(1)), (np.int64(2), np.int64(1)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(0)), (np.int64(0), np.int64(0)), (np.int64(2), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(2))]


* Using scikit-learn, we will create a Naive Bayes classifier model.  
* Steps:  
  1. Create the model  
  2. Fit the model with training data  
  3. Use the trained model to make predictions


In [18]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

# Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features, label)

# Predict Output
predicted = model.predict([[0, 2]])  # 0:Overcast, 2:Mild

print("Predicted Value:", predicted)  # 1: Yes
print("Predicted probability:", model.predict_proba([[0, 2]]))

Predicted Value: [1]
Predicted probability: [[0.00770751 0.99229249]]


> Prediction result:  
> When the weather is **Cloudy** and the temperature is **Mild**, the model predicts **"Play"**.


# Wine Classification Using Naive Bayes

We use the built-in Wine dataset from scikit-learn to create a classification model that predicts the wine classes (`class_0`, `class_1`, `class_2`).


In [19]:
# Import scikit-learn dataset library
from sklearn import datasets

# Load dataset
wine = datasets.load_wine()

# print the names of the 13 features
print("Features: ", wine.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", wine.target_names)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']


In [22]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], shape=(178, 13))

In [23]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [24]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(
    wine.data, wine.target, test_size=0.3, random_state=109
)

### Model Creation and Training

We create and train a Gaussian Naive Bayes model to classify the Wine dataset.

In [25]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

# Create a Gaussian Classifier
gnb = GaussianNB()

# Train the model
gnb.fit(X_train, y_train)

# Predict
y_pred = gnb.predict(X_test)

In a Naive Bayes model, using `predict_proba` returns the predicted probabilities for each class.


In [26]:
prob = np.round(gnb.predict_proba(X_test), 2)

prob[:5]

array([[1.  , 0.  , 0.  ],
       [0.55, 0.45, 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ]])

### Model Accuracy Evaluation

Evaluate the model using the test data and print the accuracy score.


In [27]:
gnb.score(X_test, y_test)

0.9074074074074074

In [28]:
# Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9074074074074074


# MultinomialNB Exercise

1. Replace the Gaussian Naive Bayes model (`GaussianNB`) with the Multinomial Naive Bayes model (`MultinomialNB`).  
2. Create the new model, then print the accuracy and the predicted probabilities (`predict_proba`).
