In [68]:
from matplotlib import pyplot as plt
import numpy as np

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# 🔢 Linear Algebra

In [69]:
A = np.array([[1, 2], [3, 4]])  # 2by2
B = np.array([[10, 200], [30, 400]])  # 2by2

## basic operation plus or minus

In [3]:
A + B  # pretty straight forward

array([[ 11, 202],
       [ 33, 404]])

In [4]:
A - B  # pretty straight forward

array([[  -9, -198],
       [ -27, -396]])

In [5]:
B - A  # pretty straight forward

array([[  9, 198],
       [ 27, 396]])

## Matrix mult

### element wise mutiple and division
- note that `A*B` or `A/B` is *NOT* how we do matrix product

In [6]:
A * B  # pretty straight forward

array([[  10,  400],
       [  90, 1600]])

In [7]:
np.multiply(A, B)

array([[  10,  400],
       [  90, 1600]])

In [8]:
B * A  # pretty straight forward??

array([[  10,  400],
       [  90, 1600]])

In [9]:
A / B

array([[0.1 , 0.01],
       [0.1 , 0.01]])

### matrix multiplcation: `@`, `dot`, `np.matmul`
- this is how we do matrix product
- and you will find `T` useful to `transpose`

In [10]:
A @ B  # result can be differant from  * B

array([[  70, 1000],
       [ 150, 2200]])

In [11]:
A.dot(B)

array([[  70, 1000],
       [ 150, 2200]])

In [12]:
np.matmul(A, B)  # different from np.multiply(A, B)

array([[  70, 1000],
       [ 150, 2200]])

In [13]:
B @ A

array([[ 610,  820],
       [1230, 1660]])

In [14]:
B.dot(A)

array([[ 610,  820],
       [1230, 1660]])

In [15]:
np.matmul(B, A)

array([[ 610,  820],
       [1230, 1660]])

### Summary Matrix Multiplication in NumPy: `*` vs `@`

- `A * B` performs **element-wise multiplication**.  
  - Both arrays must have the **same shape**.  
  - Each element is multiplied with its corresponding element.

- `A @ B` (or `np.matmul(A, B)`) performs **matrix multiplication**.  
  - This follows the **mathematical definition** of matrix multiplication.  
  - The **number of columns in A** must match the **number of rows in B**.


---
### ❗️Multiplying a 3×3 Matrix with a 3×2 Matrix

Example:  
- `A.shape = (3, 3)`  
- `B.shape = (3, 2)`

In this case, `A @ B` is **valid matrix multiplication**.  
But `A * B` will **raise an error** because their shapes are different and element-wise multiplication is not possible.

👉 Use `@` (or `np.matmul`) when working with actual matrix multiplication.


In [16]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 3by3
D = np.array([[6, 5], [4, 3], [2, 1]])  # 3by2

In [17]:
C @ D  # same as C.dot(D)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [18]:
D.T

array([[6, 4, 2],
       [5, 3, 1]])

In [19]:
# D @ C  # error
D.T @ C

array([[36, 48, 60],
       [24, 33, 42]])

### `linalg.inv`, `allclose`


In [20]:
A = np.array([[11, 12], [13, 14]])
A

array([[11, 12],
       [13, 14]])

In [21]:
A_inv = np.linalg.inv(A)
A_inv

array([[-7. ,  6. ],
       [ 6.5, -5.5]])

In [22]:
A @ A_inv

array([[ 1.00000000e+00, -3.55271368e-15],
       [-1.77635684e-14,  1.00000000e+00]])

In [23]:
np.round(A @ A_inv)

array([[ 1., -0.],
       [-0.,  1.]])

In [24]:
np.allclose(A @ A_inv, np.identity(2))

True

Why isn't the result exactly the identity matrix?

Due to floating point precision limits in computers, operations like matrix inversion and multiplication may result in very small numerical errors.

These tiny values (e.g., `8.88e-16`) are extremely close to zero and can be ignored.  
They appear because floating point numbers cannot represent all decimal values exactly.

To display a cleaner result, you can use `np.round()` or check equality with `np.allclose()`.

---
## `identity` & `eye`

In [25]:
print(np.identity(5))  # always sqaure
print("-" * 50)
print(np.eye(5, 5))  # sqaure or rectangle
print("-" * 50)
print(np.eye(3, 8))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
--------------------------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
--------------------------------------------------
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [26]:
A = np.array([[93, 43, 39], [43, 10, 22]])
A

array([[93, 43, 39],
       [43, 10, 22]])

In [27]:
A @ np.identity(3)  # reult must be A

array([[93., 43., 39.],
       [43., 10., 22.]])

In [28]:
A @ np.eye(3, 3)  # reult must be A

array([[93., 43., 39.],
       [43., 10., 22.]])

### 👁️ Understanding `np.eye()` and Its Use Cases

`np.eye(N, M=None, k=0)` creates a 2D array with ones on a specified diagonal and zeros elsewhere.

- It's similar to `np.identity()`, but more flexible.
- The `k` parameter lets you **shift the diagonal**:
  - `k=0`: main diagonal (default)
  - `k>0`: upper diagonals
  - `k<0`: lower diagonals

---

### When Is `np.eye()` with `k` Useful?

Some common use cases:

- **Shifting identity matrices** for specific linear algebra or signal processing tasks  
- **Delay or difference matrices** (e.g. in time series or DSP)  
- **Custom matrix patterns** for testing algorithms or simulations  
- **Creating transformation matrices** with offsets

In [29]:
np.eye(8, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.eye(3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [31]:
# 🔁 Example: First-Order Difference Matrix
n = 4
D = np.eye(n) - np.eye(n, k=-1)
print(D)
# This produces a matrix for discrete difference:

[[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -1.  1.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# Checking Performance

### time performance

In [59]:
import sys

# remember we import sys module
# An integer in Python is > 24bytes
print(sys.getsizeof(1))
print(sys.getsizeof(10**10))  # bigger number
print(sys.getsizeof(10**99))  # bigger bigger number

28
32
68


In [60]:
# Numpy size is much smaller
print(np.dtype(np.int8).itemsize)
print(np.dtype(np.int32).itemsize)
print(np.dtype(int).itemsize)

1
4
8


In [61]:
arr = np.arange(1000000)
t1 = %time np.sum(arr ** 2)
print(t1)

CPU times: user 905 μs, sys: 1.2 ms, total: 2.11 ms
Wall time: 1.99 ms
333332833333500000


In [62]:
lst = list(range(1000000))
t2 = %time sum([x ** 2 for x in lst])
print(t2)

CPU times: user 26.2 ms, sys: 8.03 ms, total: 34.2 ms
Wall time: 33.7 ms
333332833333500000


### size performance

Size of objects in Memory

In [63]:
# remember we import sys module
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [64]:
# Longs are even larger
sys.getsizeof(10**99)

68

In [65]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [66]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [67]:
# Numpy size is much smaller
np.dtype(np.float64).itemsize

8